[language-server.rust-analyzer.config]
inlayHints.bindingModeHints.enable = false
inlayHints.closingBraceHints.minLines = 10
inlayHints.closureReturnTypeHints.enable = "with_block"
inlayHints.discriminantHints.enable = "fieldless"
inlayHints.lifetimeElisionHints.enable = "skip_trivial"
inlayHints.typeHints.hideClosureInitialization = false
# diagnostics.experimantal.enable = true

[language-server.angular]
command = "bash"
args = [
  "-c",
  "ngserver --stdio --tsProbeLocations $(npm root -g) --ngProbeLocations $(npm root -g)"
]

[[language]]
name = "html"
language-servers = ["angular", "tailwindcss-ls", "vscode-html-language-server"]

[[language]]
name = "typescript"
language-servers = ["angular", "tailwindcss-ls", "typescript-language-server"]
